### ISSUE TITLE
Add proper dependency for this gem

### ISSUE THREAD

**Issue by PikachuEXE** [adamcooke/rails-safe-tasks#3]
I don't see any `require` statements in this gem
And there is no dependency declared in gemspec

You properly need `rake`, `some-gem-with-railties`

**Comment by adamcooke** [comment]
There is no need for any require statements. The library will only be required in a Rails application where `Rails::Railtie` is already available. If it isn't available, an error would be appropriate as it won't work. There's no need to require Rake as Rails handles that already and we're simply providing an additional set of tasks in the Railtie. 

The only dependency needed in the gemspec would be Rails along with what versions on Rails are required. I haven't tested in anything less than Rails 4 but it probably works fine in Rails 3 too. Feel free to submit a pull request :smile:
